Upgrade build to GHC 9.6 (#1245)
* Upgrade hevm to latest `echidna-patches` commit

* Upgrade build to GHC 9.6

* Refactor terminal and signal support in preparation for Windows UI

* Enable UI on all platforms

* Use pkgsStatic for Linux

pkgsMusl fails to build for some reason.

* Remove conditional UI compilation

All platforms now support the Echidna UI

* Enable UI on ConHost as well

See the introduction on https://hackage.haskell.org/package/ansi-terminal-1.1.1/docs/System-Console-ANSI.html

* Enable `eager-blackholing`

Observed a ~2% speedup on longer runs when compiling both hevm and
echidna with this flag. Besides, the Haskell documentation encourages
enabling it for parallel code:

https://downloads.haskell.org/~ghc/9.6.5/docs/users_guide/using-concurrent.html#compile-time-options-for-smp-parallelism

* Resolve hlint warnings

* Update Linux Stack CI to 9.6

* Fix compilation failure after merge

* Upgrade hevm to `echidna-patches-20240725`

* Fix lint warnings, unused imports

* flake: align nixpkgs with hevm

* flake: fix libiconv for x86_64 darwin

       > app/utf8-troubleshoot/cbits/locale.c:10:10: error:
       >      fatal error: 'libcharset.h' file not found
       >    |
       > 10 | #include <libcharset.h>
       >    |          ^
       > #include <libcharset.h>
       >          ^~~~~~~~~~~~~~

Also link iconv dynamically on Darwin as well