GitHub Actions: macOS: Only install needed packages
    Warning: autoconf 2.69 is already installed and up-to-date
    To reinstall 2.69, run `brew reinstall autoconf`
    Error: libtool 2.4.6_1 is already installed
    To upgrade to 2.4.6_2, run `brew upgrade libtool`.